version: '3.8'
services:
  bark-server:
    image: finab/bark-server
    container_name: bark-server
    restart: unless-stopped
    volumes:
      - /etc/bark/data:/data
    ports:
      - "8080:8080"
